/* file: model.cpp */
/*******************************************************************************
* Copyright 2014-2019 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_logitboost_Batch */

#include "daal.h"
#include "logitboost/JModel.h"

using namespace daal;
using namespace daal::algorithms;
using namespace daal::data_management;

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_logitboost_Model_cGetIterations
(JNIEnv *env, jobject thisObj, jlong modelAddr)
{
    jlong nIterations;
    logitboost::ModelPtr res = *(logitboost::ModelPtr *)modelAddr;

    nIterations = (jlong)res->getIterations();

    return nIterations;
}
