/* file: model.cpp */
/*******************************************************************************
* Copyright 2014-2016 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_logitboost_Batch */

#include "daal.h"
#include "logitboost/JModel.h"

using namespace daal;
using namespace daal::algorithms;
using namespace daal::data_management;

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_logitboost_Model_cGetIterations
(JNIEnv *env, jobject thisObj, jlong modelAddr)
{
    jlong nIterations;
    services::SharedPtr<logitboost::Model> res = *(services::SharedPtr<logitboost::Model> *)modelAddr;

    nIterations = (jlong)res->getIterations();

    return nIterations;
}
