/* file: parameter.cpp */
/*******************************************************************************
* Copyright 2014-2019 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_logitboost_Batch */

#include "daal.h"
#include "logitboost/JParameter.h"

using namespace daal;
using namespace daal::algorithms;

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cSetAccuracyThreshold
(JNIEnv *env, jobject thisObj, jlong parAddr, jdouble acc)
{
    (*(logitboost::Parameter *)parAddr).accuracyThreshold = acc;
}

JNIEXPORT jdouble JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cGetAccuracyThreshold
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return(jdouble)(*(logitboost::Parameter *)parAddr).accuracyThreshold;
}

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cSetWeightsThreshold
(JNIEnv *env, jobject thisObj, jlong parAddr, jdouble acc)
{
    (*(logitboost::Parameter *)parAddr).weightsDegenerateCasesThreshold = acc;
}

JNIEXPORT jdouble JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cGetWeightsThreshold
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return(jdouble)(*(logitboost::Parameter *)parAddr).weightsDegenerateCasesThreshold;
}

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cSetResponsesThreshold
(JNIEnv *env, jobject thisObj, jlong parAddr, jdouble acc)
{
    (*(logitboost::Parameter *)parAddr).responsesDegenerateCasesThreshold = acc;
}

JNIEXPORT jdouble JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cGetResponsesThreshold
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return(jdouble)(*(logitboost::Parameter *)parAddr).responsesDegenerateCasesThreshold;
}

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cSetMaxIterations
(JNIEnv *env, jobject thisObj, jlong parAddr, jlong nIter)
{
    (*(logitboost::Parameter *)parAddr).maxIterations = nIter;
}

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cGetMaxIterations
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return(jlong)(*(logitboost::Parameter *)parAddr).maxIterations;
}

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cSetNClasses
(JNIEnv *env, jobject thisObj, jlong parAddr, jlong nIter)
{
    (*(logitboost::Parameter *)parAddr).nClasses = nIter;
}

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_logitboost_Parameter_cGetNClasses
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return(jlong)(*(logitboost::Parameter *)parAddr).nClasses;
}
