/* file: distributedmasterinput.cpp */
/*******************************************************************************
* Copyright 2014-2018 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_algorithms_pca_Offline */

#include "daal.h"
#include "pca/JMethod.h"
#include "pca/JDistributedStep2MasterInput.h"

#include "common_helpers.h"

#define CorrelationDenseValue com_intel_daal_algorithms_pca_Method_correlationDenseValue
#define SVDDenseValue         com_intel_daal_algorithms_pca_Method_svdDenseValue

USING_COMMON_NAMESPACES();
using namespace daal::algorithms::pca;

/*
 * Class:     com_intel_daal_algorithms_pca_DistributedStep2MasterInput
 * Method:    cAddInput
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_pca_DistributedStep2MasterInput_cAddInput
(JNIEnv *env, jobject thisObj, jlong inputAddr, jint id, jlong partialResultAddr, jint method)
{
    if(method == CorrelationDenseValue)
    {
        jniInput<DistributedInput<correlationDense> >::
            add<Step2MasterInputId, pca::PartialResult<correlationDense> >(inputAddr, id, partialResultAddr);
    }
    else if(method == SVDDenseValue)
    {
        jniInput<DistributedInput<svdDense> >::
            add<Step2MasterInputId, pca::PartialResult<svdDense> >(inputAddr, id, partialResultAddr);
    }
}
