pull_request_rules:
  - name: backport patches to 2021 branch
    conditions:
      - base=master
      - label=backport-2021
    actions:
      backport:
        branches:
          - rls/2021-gold-mnt
        ignore_conflicts: true
  - name: delete head branch after merge
    conditions:
      - head~=^renovate/
      - merged
    actions:
      delete_head_branch: {}
  - name: Review assigment for renovate requests
    conditions:
      - author=renovate[bot]
      - -closed
    actions:
      label:
        add: [infra]
      request_reviews:
        users:
          - napetrov
          - vmeshche
  - name: automatic merge on renovate updates for documentation
    conditions:
      - author=renovate[bot]
      - check-success=docbuild
      - files=docs/requirements.txt
      - "#files=1"
    actions:
      merge:
        method: merge

