#===============================================================================
# Copyright 2014-2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) Data Analytics Acceleration Library algorithms list
##******************************************************************************

CORE.ALGORITHMS.CUSTOM.AVAILABLE := low_order_moments quantiles covariance cosdistance cordistance kmeans pca cholesky \
                svd assocrules qr em outlierdetection_bacon outlierdetection_multivariate outlierdetection_univariate  \
                kernel_function sorting normalization optimization_solver objective_function decision_tree             \
                dtrees/gbt dtrees/forest linear_regression ridge_regression naivebayes stump adaboost brownboost       \
                logitboost svm multiclassclassifier k_nearest_neighbors logistic_regression implicit_als               \
                coordinate_descent

low_order_moments +=
quantiles +=
covariance +=
cosdistance +=
cordistance += covariance
elastic_net += linear_model regression optimization_solver objective_function engines
kmeans += kmeans/inner engines distributions
pca += pca/inner pca/metrics pca/transform svd covariance low_order_moments normalization
cholesky +=
svd +=
assocrules +=
qr +=
em += covariance engines distributions
outlierdetection_bacon +=
outlierdetection_multivariate +=
outlierdetection_univariate +=
kernel_function +=
sorting +=
normalization += normalization/minmax normalization/zscore normalization/zscore/inner low_order_moments
optimization_solver += optimization_solver/adagrad optimization_solver/adagrad/inner optimization_solver/lbfgs optimization_solver/lbfgs/inner optimization_solver/sgd optimization_solver/sgd/inner optimization_solver/saga optimization_solver/saga/inner optimization_solver/inner optimization_solver/coordinate_descent objective_function engines distributions
coordinate_descent += optimization_solver/coordinate_descent objective_function engines distributions
objective_function += objective_function/inner objective_function/cross_entropy_loss objective_function/cross_entropy_loss/inner objective_function/logistic_loss objective_function/logistic_loss/inner objective_function/mse objective_function/mse/inner
decision_tree += decision_tree/inner regression classifier classifier/inner
dtrees/gbt += dtrees dtrees/gbt/classification dtrees/gbt/classification/inner dtrees/gbt/regression engines classifier classifier/inner regression objective_function
dtrees/forest += dtrees dtrees/regression dtrees/forest/classification dtrees/forest/classification/inner dtrees/forest/regression engines classifier classifier/inner regression distributions
linear_regression += linear_model regression
lasso_regression += linear_model regression optimization_solver objective_function engines
ridge_regression += linear_model regression
naivebayes += classifier classifier/inner
stump += stump/inner classifier classifier/inner weak_learner/inner
adaboost += adaboost/inner classifier classifier/inner decision_tree decision_tree/inner stump stump/inner boosting/inner weak_learner/inner
brownboost += brownboost/inner boosting/inner weak_learner/inner classifier classifier/inner decision_tree decision_tree/inner stump stump/inner
logitboost += logitboost/inner boosting/inner weak_learner/inner classifier classifier/inner regression decision_tree decision_tree/inner stump stump/inner
svm +=  svm/inner classifier classifier/inner kernel_function multiclassclassifier multiclassclassifier/inner
multiclassclassifier += multiclassclassifier/inner classifier classifier/inner
k_nearest_neighbors += k_nearest_neighbors/inner engines classifier classifier/inner
logistic_regression += logistic_regression/inner classifier classifier/inner optimization_solver objective_function engines
implicit_als += engines distributions
engines += engines/mt19937 engines/mcg59 engines/mt2203
distributions += distributions/bernoulli distributions/normal distributions/uniform

CORE.ALGORITHMS.FULL :=                                                       \
    logistic_regression                                                       \
    logistic_regression/inner                                                 \
    svm                                                                       \
    svm/inner                                                                 \


CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$(foreach alg2,$($(alg1)),$($(alg2)) $(alg2)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    association_rules                                                         \
    boosting                                                                  \
    cholesky                                                                  \
    classifier                                                                \
    covariance                                                                \
    decision_forest                                                           \
    decision_tree                                                             \
    distance                                                                  \
    distributions                                                             \
    dbscan                                                                    \
    elastic_net                                                               \
    engines                                                                   \
    em                                                                        \
    gradient_boosted_trees                                                    \
    implicit_als                                                              \
    kernel_function                                                           \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lasso_regression                                                          \
    linear_model                                                              \
    linear_regression                                                         \
    logistic_regression                                                       \
    moments                                                                   \
    multi_class_classifier                                                    \
    naive_bayes                                                               \
    normalization                                                             \
    optimization_solver                                                       \
    optimization_solver/adagrad                                               \
    optimization_solver/iterative_solver                                      \
    optimization_solver/lbfgs                                                 \
    optimization_solver/objective_function                                    \
    optimization_solver/precomputed                                           \
    optimization_solver/sgd                                                   \
    optimization_solver/saga                                                  \
    optimization_solver/coordinate_descent                                    \
    outlier_detection                                                         \
    pca                                                                       \
    pca/metrics                                                               \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    quantiles                                                                 \
    regression                                                                \
    ridge_regression                                                          \
    sorting                                                                   \
    stump                                                                     \
    svd                                                                       \
    svm                                                                       \
    tree_utils                                                                \
    weak_learner


CORE.SERVICES       := compression            \
                       data_management

JJ.ALGORITHMS       := svm                                                       \


JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source                                               \
                       compression                                               \
                       compression/bzip2                                         \
                       compression/lzo                                           \
                       compression/rle                                           \
                       compression/zlib
