#===============================================================================
# Copyright 2014 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) oneAPI Data Analytics Library algorithms list
##******************************************************************************

CORE.ALGORITHMS.CUSTOM.AVAILABLE := low_order_moments quantiles covariance cosdistance cordistance kmeans pca cholesky \
                svd assocrules qr em outlierdetection_bacon outlierdetection_multivariate outlierdetection_univariate  \
                kernel_function sorting normalization optimization_solver objective_function decision_tree             \
                dtrees/gbt dtrees/forest linear_regression ridge_regression naivebayes stump adaboost brownboost       \
                logitboost svm multiclassclassifier k_nearest_neighbors logistic_regression implicit_als               \
                coordinate_descent jaccard triangle_counting shortest_paths subgraph_isomorphism connected_components  \
                louvain tsne spectral_embedding

classifier += classifier/inner
low_order_moments +=
quantiles +=
covariance +=
cosdistance +=
cordistance += covariance
elastic_net += linear_model regression optimization_solver objective_function engines
kmeans += engines distributions
pca += pca/metrics pca/transform svd covariance low_order_moments normalization
cholesky +=
svd +=
assocrules +=
qr +=
em += covariance engines distributions
outlierdetection_bacon +=
outlierdetection_multivariate +=
outlierdetection_univariate +=
kernel_function += kernel_function/polynomial
sorting +=
normalization += normalization/minmax normalization/zscore low_order_moments
optimization_solver += optimization_solver/adagrad optimization_solver/lbfgs optimization_solver/sgd optimization_solver/saga optimization_solver/coordinate_descent objective_function engines distributions
coordinate_descent += optimization_solver/coordinate_descent objective_function engines distributions
objective_function += objective_function/cross_entropy_loss objective_function/logistic_loss objective_function/mse
decision_tree += regression classifier
dtrees/gbt += dtrees dtrees/gbt/classification dtrees/gbt/regression engines classifier regression objective_function
dtrees/forest += dtrees dtrees/regression dtrees/forest/classification dtrees/forest/regression engines classifier regression distributions
linear_regression += linear_model regression
lasso_regression += linear_model regression optimization_solver objective_function engines
ridge_regression += linear_model regression
naivebayes += classifier
stump += classifier
adaboost += classifier decision_tree stump
brownboost += classifier decision_tree stump
logitboost += classifier regression decision_tree stump
svm += classifier kernel_function multiclassclassifier
multiclassclassifier += classifier
k_nearest_neighbors += engines classifier
logistic_regression += classifier optimization_solver objective_function engines
implicit_als += engines distributions
engines += engines/mt19937 engines/mcg59 engines/mt2203
distributions += distributions/bernoulli distributions/normal distributions/uniform
tsne +=
spectral_embedding += cosdistance

CORE.ALGORITHMS.FULL :=                                                       \
    adaboost                                                                  \
    assocrules                                                                \
    brownboost                                                                \
    cholesky                                                                  \
    classifier                                                                \
    cordistance                                                               \
    cosdistance                                                               \
    covariance                                                                \
    decision_tree                                                             \
    distributions                                                             \
    distributions/bernoulli                                                   \
    distributions/normal                                                      \
    distributions/uniform                                                     \
    dtrees                                                                    \
    dtrees/forest                                                             \
    dtrees/forest/classification                                              \
    dtrees/forest/regression                                                  \
    dtrees/gbt                                                                \
    dtrees/gbt/regression                                                     \
    dtrees/gbt/classification                                                 \
    dtrees/regression                                                         \
    dbscan                                                                    \
    elastic_net                                                               \
    engines                                                                   \
    engines/mcg59                                                             \
    engines/mt19937                                                           \
    engines/mt2203                                                            \
    em                                                                        \
    implicit_als                                                              \
    kernel_function                                                           \
    kernel_function/polynomial                                                \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lbfgs                                                                     \
    linear_model                                                              \
    lasso_regression                                                          \
    linear_regression                                                         \
    logistic_regression                                                       \
    logitboost                                                                \
    low_order_moments                                                         \
    multiclassclassifier                                                      \
    naivebayes                                                                \
    normalization/minmax                                                      \
    normalization/zscore                                                      \
    objective_function                                                        \
    objective_function/cross_entropy_loss                                     \
    objective_function/logistic_loss                                          \
    objective_function/mse                                                    \
    optimization_solver                                                       \
    optimization_solver/sgd                                                   \
    optimization_solver/lbfgs                                                 \
    optimization_solver/adagrad                                               \
    optimization_solver/saga                                                  \
    optimization_solver/coordinate_descent                                    \
    outlierdetection_multivariate                                             \
    outlierdetection_bacon                                                    \
    outlierdetection_univariate                                               \
    pca                                                                       \
    pca/metrics                                                               \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    quantiles                                                                 \
    regression                                                                \
    ridge_regression                                                          \
    sgd                                                                       \
    sorting                                                                   \
    stump                                                                     \
    svd                                                                       \
    svm                                                                       \
    weak_learner/inner                                                        \
    tsne                                                                      \
    spectral_embedding

CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$(foreach alg2,$($(alg1)),$($(alg2)) $(alg2)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    association_rules                                                         \
    boosting                                                                  \
    cholesky                                                                  \
    classifier                                                                \
    covariance                                                                \
    decision_forest                                                           \
    decision_tree                                                             \
    distance                                                                  \
    distributions                                                             \
    dbscan                                                                    \
    elastic_net                                                               \
    engines                                                                   \
    em                                                                        \
    gradient_boosted_trees                                                    \
    implicit_als                                                              \
    kernel_function                                                           \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lasso_regression                                                          \
    linear_model                                                              \
    linear_regression                                                         \
    logistic_regression                                                       \
    moments                                                                   \
    multi_class_classifier                                                    \
    naive_bayes                                                               \
    normalization                                                             \
    optimization_solver                                                       \
    optimization_solver/adagrad                                               \
    optimization_solver/iterative_solver                                      \
    optimization_solver/lbfgs                                                 \
    optimization_solver/objective_function                                    \
    optimization_solver/precomputed                                           \
    optimization_solver/sgd                                                   \
    optimization_solver/saga                                                  \
    optimization_solver/coordinate_descent                                    \
    outlier_detection                                                         \
    pca                                                                       \
    pca/metrics                                                               \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    quantiles                                                                 \
    regression                                                                \
    ridge_regression                                                          \
    sorting                                                                   \
    stump                                                                     \
    svd                                                                       \
    svm                                                                       \
    tree_utils                                                                \
    weak_learner                                                              \
    tsne


CORE.SERVICES       := data_management

# Dependencies between oneAPI and core (CPU-only) algorithms
ONEAPI.ALGOS.basic_statistics := CORE.moments
ONEAPI.ALGOS.covariance    := CORE.covariance
ONEAPI.ALGOS.dbscan := CORE.dbscan
ONEAPI.ALGOS.decision_forest := CORE.decision_forest decision_tree
ONEAPI.ALGOS.kmeans := CORE.kmeans
ONEAPI.ALGOS.kmeans_init := CORE.kmeans
ONEAPI.ALGOS.knn := CORE.k_nearest_neighbors
ONEAPI.ALGOS.linear_kernel := CORE.kernel_function
ONEAPI.ALGOS.objective_function := CORE.objective_function
ONEAPI.ALGOS.pca           := CORE.pca
ONEAPI.ALGOS.polynomial_kernel := CORE.kernel_function
ONEAPI.ALGOS.sigmoid_kernel := CORE.kernel_function
ONEAPI.ALGOS.rbf_kernel    := CORE.kernel_function
ONEAPI.ALGOS.spectral_embedding := CORE.spectral_embedding
ONEAPI.ALGOS.svm           := CORE.svm

# List of algorithms in oneAPI part

ONEAPI.ALGOS :=          \
    basic_statistics     \
    chebyshev_distance   \
    cosine_distance      \
    covariance           \
    dbscan               \
    decision_forest      \
    decision_tree        \
    finiteness_checker   \
    kmeans               \
    kmeans_init          \
    knn                  \
    linear_kernel        \
    linear_regression    \
    logistic_regression  \
    logloss_objective    \
    louvain              \
    newton_cg            \
    minkowski_distance   \
    objective_function   \
    pca                  \
    polynomial_kernel    \
    sigmoid_kernel       \
    rbf_kernel           \
    spectral_embedding   \
    svm                  \
    jaccard              \
    triangle_counting    \
    shortest_paths       \
    subgraph_isomorphism \
    connected_components


ONEAPI.IO :=     \
    csv

JJ.ALGORITHMS       := adaboost                                                  \
                       adaboost/prediction                                       \
                       adaboost/quality_metric_set                               \
                       adaboost/training                                         \
                       association_rules                                         \
                       bacon_outlier_detection                                   \
                       bf_knn_classification                                     \
                       bf_knn_classification/prediction                          \
                       bf_knn_classification/training                            \
                       binary_adaboost                                           \
                       binary_adaboost/prediction                                \
                       binary_adaboost/quality_metric_set                        \
                       binary_adaboost/training                                  \
                       boosting                                                  \
                       boosting/prediction                                       \
                       boosting/training                                         \
                       brownboost                                                \
                       brownboost/prediction                                     \
                       brownboost/quality_metric_set                             \
                       brownboost/training                                       \
                       cholesky                                                  \
                       classifier                                                \
                       classifier/prediction                                     \
                       classifier/quality_metric                                 \
                       classifier/quality_metric/binary_confusion_matrix         \
                       classifier/quality_metric/multi_class_confusion_matrix    \
                       classifier/training                                       \
                       cordistance                                               \
                       cosdistance                                               \
                       covariance                                                \
                       dbscan                                                    \
                       decision_forest                                           \
                       decision_forest/classification                            \
                       decision_forest/classification/prediction                 \
                       decision_forest/classification/training                   \
                       decision_forest/regression                                \
                       decision_forest/regression/prediction                     \
                       decision_forest/regression/training                       \
                       decision_tree                                             \
                       decision_tree/classification                              \
                       decision_tree/classification/prediction                   \
                       decision_tree/classification/training                     \
                       decision_tree/regression                                  \
                       decision_tree/regression/prediction                       \
                       decision_tree/regression/training                         \
                       distributions                                             \
                       distributions/bernoulli                                   \
                       distributions/normal                                      \
                       distributions/uniform                                     \
                       elastic_net                                               \
                       elastic_net/training                                      \
                       elastic_net/prediction                                    \
                       engines                                                   \
                       engines/mcg59                                             \
                       engines/mt19937                                           \
                       engines/mt2203                                            \
                       em_gmm                                                    \
                       em_gmm/init                                               \
                       gbt                                                       \
                       gbt/classification                                        \
                       gbt/classification/prediction                             \
                       gbt/classification/training                               \
                       gbt/regression                                            \
                       gbt/regression/prediction                                 \
                       gbt/regression/training                                   \
                       gbt/training                                              \
                       implicit_als                                              \
                       implicit_als/prediction                                   \
                       implicit_als/prediction/ratings                           \
                       implicit_als/training                                     \
                       implicit_als/training/init                                \
                       kernel_function                                           \
                       kernel_function/linear                                    \
                       kernel_function/rbf                                       \
                       kdtree_knn_classification                                 \
                       kdtree_knn_classification/prediction                      \
                       kdtree_knn_classification/training                        \
                       kmeans                                                    \
                       kmeans/init                                               \
                       lasso_regression                                          \
                       lasso_regression/training                                 \
                       lasso_regression/prediction                               \
                       linear_regression                                         \
                       linear_regression/prediction                              \
                       linear_regression/quality_metric                          \
                       linear_regression/quality_metric_set                      \
                       linear_regression/training                                \
                       logistic_regression                                       \
                       logistic_regression/prediction                            \
                       logistic_regression/training                              \
                       logitboost                                                \
                       logitboost/prediction                                     \
                       logitboost/quality_metric_set                             \
                       logitboost/training                                       \
                       low_order_moments                                         \
                       multi_class_classifier                                    \
                       multi_class_classifier/prediction                         \
                       multi_class_classifier/quality_metric_set                 \
                       multi_class_classifier/training                           \
                       multinomial_naive_bayes                                   \
                       multinomial_naive_bayes/prediction                        \
                       multinomial_naive_bayes/quality_metric_set                \
                       multinomial_naive_bayes/training                          \
                       multivariate_outlier_detection                            \
                       multivariate_outlier_detection/defaultdense               \
                       multivariate_outlier_detection/bacondense                 \
                       normalization/minmax                                      \
                       normalization/zscore                                      \
                       optimization_solver                                       \
                       optimization_solver/cross_entropy_loss                    \
                       optimization_solver/logistic_loss                         \
                       optimization_solver/objective_function                    \
                       optimization_solver/sum_of_functions                      \
                       optimization_solver/mse                                   \
                       optimization_solver/precomputed                           \
                       optimization_solver/iterative_solver                      \
                       optimization_solver/sgd                                   \
                       optimization_solver/saga                                  \
                       optimization_solver/coordinate_descent                    \
                       optimization_solver/lbfgs                                 \
                       optimization_solver/adagrad                               \
                       pca                                                       \
                       pca/quality_metric                                        \
                       pca/quality_metric_set                                    \
                       pca/transform                                             \
                       pivoted_qr                                                \
                       qr                                                        \
                       quality_metric                                            \
                       quality_metric_set                                        \
                       quantiles                                                 \
                       ridge_regression                                          \
                       ridge_regression/prediction                               \
                       ridge_regression/training                                 \
                       regression                                                \
                       regression/training                                       \
                       regression/prediction                                     \
                       sorting                                                   \
                       stump                                                     \
                       stump/prediction                                          \
                       stump/training                                            \
                       stump/classification                                      \
                       stump/classification/training                             \
                       stump/classification/prediction                           \
                       stump/regression                                          \
                       stump/regression/training                                 \
                       stump/regression/prediction                               \
                       svd                                                       \
                       svm                                                       \
                       svm/prediction                                            \
                       svm/quality_metric_set                                    \
                       svm/training                                              \
                       tree_utils                                                \
                       tree_utils/classification                                 \
                       tree_utils/regression                                     \
                       univariate_outlier_detection                              \
                       weak_learner                                              \
                       weak_learner/prediction                                   \
                       weak_learner/training

JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source
