#===============================================================================
# Copyright 2014-2019 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

##  Content:
##     Intel(R) Data Analytics Acceleration Library algorithms list
##******************************************************************************

CORE.ALGORITHMS.CUSTOM.AVAILABLE := low_order_moments quantiles covariance cosdistance cordistance kmeans pca cholesky \
                svd assocrules qr em outlierdetection_bacon outlierdetection_multivariate outlierdetection_univariate  \
                kernel_function sorting normalization math optimization_solver objective_function decision_tree        \
                dtrees/gbt dtrees/forest linear_regression ridge_regression naivebayes stump adaboost brownboost       \
                logitboost svm multiclassclassifier k_nearest_neighbors logistic_regression implicit_als               \
                neural_networks coordinate_descent

low_order_moments +=
quantiles +=
covariance +=
cosdistance +=
cordistance += covariance
kmeans += kmeans/inner engines distributions
pca += pca/inner pca/metrics pca/transform svd covariance low_order_moments normalization
cholesky +=
svd +=
assocrules +=
qr +=
em += covariance engines distributions
outlierdetection_bacon +=
outlierdetection_multivariate +=
outlierdetection_univariate +=
kernel_function +=
sorting +=
normalization += normalization/minmax normalization/zscore normalization/zscore/inner low_order_moments
math += math/abs math/logistic math/relu math/smoothrelu math/softmax math/tanh
optimization_solver += optimization_solver/adagrad optimization_solver/adagrad/inner optimization_solver/lbfgs optimization_solver/lbfgs/inner optimization_solver/sgd optimization_solver/sgd/inner optimization_solver/saga optimization_solver/saga/inner optimization_solver/inner optimization_solver/coordinate_descent objective_function engines distributions
coordinate_descent += optimization_solver/coordinate_descent objective_function engines distributions
objective_function += objective_function/inner objective_function/cross_entropy_loss objective_function/cross_entropy_loss/inner objective_function/logistic_loss objective_function/logistic_loss/inner objective_function/mse objective_function/mse/inner
decision_tree += regression classifier
dtrees/gbt += dtrees dtrees/gbt/classification dtrees/gbt/regression engines classifier regression objective_function
dtrees/forest += dtrees dtrees/regression dtrees/forest/classification dtrees/forest/regression engines classifier regression distributions
linear_regression += linear_model regression
lasso_regression += linear_model regression optimization_solver objective_function engines
ridge_regression += linear_model regression
naivebayes += classifier
stump += classifier 
adaboost += classifier decision_tree stump boosting weak_learner adaboost/inner
brownboost += brownboost/inner boosting/inner weak_learner classifier decision_tree stump
logitboost += logitboost/inner boosting/inner weak_learner classifier regression decision_tree stump
svm +=  svm/inner classifier kernel_function multiclassclassifier
multiclassclassifier += classifier
k_nearest_neighbors += engines classifier
logistic_regression += logistic_regression/inner classifier optimization_solver objective_function engines
implicit_als += engines distributions
  neural_networks_layers := $(addprefix neural_networks/layers/,abs_layer batch_normalization_layer concat_layer convolution2d_layer dropout_layer eltwise_sum_layer elu_layer fullyconnected_layer lcn_layer locallyconnected2d_layer logistic_layer loss_layer loss_layer/logistic_cross_layer loss_layer/softmax_cross_layer lrn_layer pooling1d_layer pooling2d_layer pooling3d_layer prelu_layer relu_layer reshape_layer smoothrelu_layer softmax_layer spatial_pooling2d_layer split_layer tanh_layer transposed_conv2d_layer)
neural_networks += engines optimization_solver distributions \
                   neural_networks/initializers neural_networks/initializers/gaussian neural_networks/initializers/truncated_gaussian neural_networks/initializers/uniform neural_networks/initializers/xavier \
                   neural_networks/layers $(neural_networks_layers) $(addsuffix /backward,$(neural_networks_layers)) $(addsuffix /forward,$(neural_networks_layers))
engines += engines/mt19937 engines/mcg59 engines/mt2203
distributions += distributions/bernoulli distributions/normal distributions/uniform

CORE.ALGORITHMS.FULL :=                                                       \
    adaboost                                                                  \
    adaboost/inner                                                            \
    assocrules                                                                \
    boosting/inner                                                            \
    brownboost                                                                \
    brownboost/inner                                                          \
    cholesky                                                                  \
    classifier                                                                \
    cordistance                                                               \
    cosdistance                                                               \
    covariance                                                                \
    decision_tree                                                             \
    distributions                                                             \
    distributions/bernoulli                                                   \
    distributions/normal                                                      \
    distributions/uniform                                                     \
    dtrees                                                                    \
    dtrees/forest                                                             \
    dtrees/forest/classification                                              \
    dtrees/forest/regression                                                  \
    dtrees/gbt                                                                \
    dtrees/gbt/regression                                                     \
    dtrees/gbt/classification                                                 \
    dtrees/regression                                                         \
    dbscan                                                                    \
    engines                                                                   \
    engines/mcg59                                                             \
    engines/mt19937                                                           \
    engines/mt2203                                                            \
    em                                                                        \
    implicit_als                                                              \
    kernel_function                                                           \
    kmeans/inner                                                              \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lbfgs                                                                     \
    linear_model                                                              \
    lasso_regression                                                          \
    linear_regression                                                         \
    logistic_regression                                                       \
    logistic_regression/inner                                                 \
    logitboost                                                                \
    low_order_moments                                                         \
    math/abs                                                                  \
    math/logistic                                                             \
    math/relu                                                                 \
    math/smoothrelu                                                           \
    math/softmax                                                              \
    math/tanh                                                                 \
    multiclassclassifier                                                      \
    naivebayes                                                                \
    neural_networks                                                           \
    neural_networks/initializers                                              \
    neural_networks/initializers/uniform                                      \
    neural_networks/initializers/xavier                                       \
    neural_networks/initializers/gaussian                                     \
    neural_networks/initializers/truncated_gaussian                           \
    neural_networks/layers                                                    \
    neural_networks/layers/abs_layer                                          \
    neural_networks/layers/abs_layer/backward                                 \
    neural_networks/layers/abs_layer/forward                                  \
    neural_networks/layers/batch_normalization_layer                          \
    neural_networks/layers/batch_normalization_layer/backward                 \
    neural_networks/layers/batch_normalization_layer/forward                  \
    neural_networks/layers/concat_layer                                       \
    neural_networks/layers/concat_layer/backward                              \
    neural_networks/layers/concat_layer/forward                               \
    neural_networks/layers/convolution2d_layer                                \
    neural_networks/layers/convolution2d_layer/backward                       \
    neural_networks/layers/convolution2d_layer/forward                        \
    neural_networks/layers/dropout_layer                                      \
    neural_networks/layers/dropout_layer/backward                             \
    neural_networks/layers/dropout_layer/forward                              \
    neural_networks/layers/eltwise_sum_layer                                  \
    neural_networks/layers/eltwise_sum_layer/backward                         \
    neural_networks/layers/eltwise_sum_layer/forward                          \
    neural_networks/layers/fullyconnected_layer                               \
    neural_networks/layers/fullyconnected_layer/backward                      \
    neural_networks/layers/fullyconnected_layer/forward                       \
    neural_networks/layers/lcn_layer                                          \
    neural_networks/layers/lcn_layer/backward                                 \
    neural_networks/layers/lcn_layer/forward                                  \
    neural_networks/layers/locallyconnected2d_layer                           \
    neural_networks/layers/locallyconnected2d_layer/backward                  \
    neural_networks/layers/locallyconnected2d_layer/forward                   \
    neural_networks/layers/logistic_layer                                     \
    neural_networks/layers/logistic_layer/backward                            \
    neural_networks/layers/logistic_layer/forward                             \
    neural_networks/layers/reshape_layer                                      \
    neural_networks/layers/reshape_layer/backward                             \
    neural_networks/layers/reshape_layer/forward                              \
    neural_networks/layers/lrn_layer                                          \
    neural_networks/layers/lrn_layer/backward                                 \
    neural_networks/layers/lrn_layer/forward                                  \
    neural_networks/layers/pooling1d_layer                                    \
    neural_networks/layers/pooling1d_layer/backward                           \
    neural_networks/layers/pooling1d_layer/forward                            \
    neural_networks/layers/pooling2d_layer                                    \
    neural_networks/layers/pooling2d_layer/backward                           \
    neural_networks/layers/pooling2d_layer/forward                            \
    neural_networks/layers/pooling3d_layer                                    \
    neural_networks/layers/pooling3d_layer/backward                           \
    neural_networks/layers/pooling3d_layer/forward                            \
    neural_networks/layers/spatial_pooling2d_layer                            \
    neural_networks/layers/spatial_pooling2d_layer/backward                   \
    neural_networks/layers/spatial_pooling2d_layer/forward                    \
    neural_networks/layers/prelu_layer                                        \
    neural_networks/layers/prelu_layer/backward                               \
    neural_networks/layers/prelu_layer/forward                                \
    neural_networks/layers/elu_layer                                          \
    neural_networks/layers/elu_layer/backward                                 \
    neural_networks/layers/elu_layer/forward                                  \
    neural_networks/layers/relu_layer                                         \
    neural_networks/layers/relu_layer/backward                                \
    neural_networks/layers/relu_layer/forward                                 \
    neural_networks/layers/smoothrelu_layer                                   \
    neural_networks/layers/smoothrelu_layer/backward                          \
    neural_networks/layers/smoothrelu_layer/forward                           \
    neural_networks/layers/loss_layer                                         \
    neural_networks/layers/loss_layer/logistic_cross_layer                    \
    neural_networks/layers/loss_layer/logistic_cross_layer/backward           \
    neural_networks/layers/loss_layer/logistic_cross_layer/forward            \
    neural_networks/layers/loss_layer/softmax_cross_layer                     \
    neural_networks/layers/loss_layer/softmax_cross_layer/backward            \
    neural_networks/layers/loss_layer/softmax_cross_layer/forward             \
    neural_networks/layers/softmax_layer                                      \
    neural_networks/layers/softmax_layer/backward                             \
    neural_networks/layers/softmax_layer/forward                              \
    neural_networks/layers/split_layer                                        \
    neural_networks/layers/split_layer/backward                               \
    neural_networks/layers/split_layer/forward                                \
    neural_networks/layers/tanh_layer                                         \
    neural_networks/layers/tanh_layer/backward                                \
    neural_networks/layers/tanh_layer/forward                                 \
    neural_networks/layers/transposed_conv2d_layer                            \
    neural_networks/layers/transposed_conv2d_layer/backward                   \
    neural_networks/layers/transposed_conv2d_layer/forward                    \
    normalization/minmax                                                      \
    normalization/zscore                                                      \
    normalization/zscore/inner                                                \
    objective_function                                                        \
    objective_function/inner                                                  \
    objective_function/cross_entropy_loss                                     \
    objective_function/cross_entropy_loss/inner                               \
    objective_function/logistic_loss                                          \
    objective_function/logistic_loss/inner                                    \
    objective_function/mse                                                    \
    objective_function/mse/inner                                              \
    optimization_solver                                                       \
    optimization_solver/inner                                                 \
    optimization_solver/sgd                                                   \
    optimization_solver/sgd/inner                                             \
    optimization_solver/lbfgs                                                 \
    optimization_solver/lbfgs/inner                                           \
    optimization_solver/adagrad                                               \
    optimization_solver/adagrad/inner                                         \
    optimization_solver/saga                                                  \
    optimization_solver/saga/inner                                            \
    optimization_solver/coordinate_descent                                    \
    outlierdetection_multivariate                                             \
    outlierdetection_bacon                                                    \
    outlierdetection_univariate                                               \
    pca                                                                       \
    pca/inner                                                                 \
    pca/metrics                                                               \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    quantiles                                                                 \
    regression                                                                \
    ridge_regression                                                          \
    sgd                                                                       \
    sorting                                                                   \
    stump                                                                     \
    svd                                                                       \
    svm                                                                       \
    svm/inner                                                                 \
    weak_learner


CORE.ALGORITHMS := $(if $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.CUSTOM), $(CORE.ALGORITHMS.FULL))
CORE.ALGORITHMS := $(sort $(foreach alg,$(CORE.ALGORITHMS),$(foreach alg1,$($(alg)),$(foreach alg2,$($(alg1)),$($(alg2)) $(alg2)) $(alg1)) $(alg)))

CORE.ALGORITHMS.INC :=                                                        \
    association_rules                                                         \
    boosting                                                                  \
    cholesky                                                                  \
    classifier                                                                \
    covariance                                                                \
    decision_forest                                                           \
    decision_tree                                                             \
    distance                                                                  \
    distributions                                                             \
    dbscan                                                                    \
    engines                                                                   \
    em                                                                        \
    gradient_boosted_trees                                                    \
    implicit_als                                                              \
    kernel_function                                                           \
    kmeans                                                                    \
    k_nearest_neighbors                                                       \
    lasso_regression                                                          \
    linear_model                                                              \
    linear_regression                                                         \
    logistic_regression                                                       \
    math                                                                      \
    moments                                                                   \
    multi_class_classifier                                                    \
    naive_bayes                                                               \
    neural_networks                                                           \
    neural_networks/initializers                                              \
    neural_networks/initializers/gaussian                                     \
    neural_networks/initializers/truncated_gaussian                           \
    neural_networks/initializers/uniform                                      \
    neural_networks/initializers/xavier                                       \
    neural_networks/layers                                                    \
    neural_networks/layers/abs                                                \
    neural_networks/layers/batch_normalization                                \
    neural_networks/layers/concat                                             \
    neural_networks/layers/convolution2d                                      \
    neural_networks/layers/dropout                                            \
    neural_networks/layers/fullyconnected                                     \
    neural_networks/layers/lcn                                                \
    neural_networks/layers/locallyconnected2d                                 \
    neural_networks/layers/logistic                                           \
    neural_networks/layers/loss                                               \
    neural_networks/layers/lrn                                                \
    neural_networks/layers/pooling1d                                          \
    neural_networks/layers/pooling2d                                          \
    neural_networks/layers/pooling3d                                          \
    neural_networks/layers/prelu                                              \
    neural_networks/layers/elu                                                \
    neural_networks/layers/relu                                               \
    neural_networks/layers/reshape                                            \
    neural_networks/layers/smoothrelu                                         \
    neural_networks/layers/softmax                                            \
    neural_networks/layers/spatial_pooling2d                                  \
    neural_networks/layers/split                                              \
    neural_networks/layers/tanh                                               \
    neural_networks/layers/transposed_conv2d                                  \
    neural_networks/layers/eltwise_sum                                        \
    normalization                                                             \
    optimization_solver                                                       \
    optimization_solver/adagrad                                               \
    optimization_solver/iterative_solver                                      \
    optimization_solver/lbfgs                                                 \
    optimization_solver/objective_function                                    \
    optimization_solver/precomputed                                           \
    optimization_solver/sgd                                                   \
    optimization_solver/saga                                                  \
    optimization_solver/coordinate_descent                                    \
    outlier_detection                                                         \
    pca                                                                       \
    pca/metrics                                                               \
    pca/transform                                                             \
    pivoted_qr                                                                \
    qr                                                                        \
    quantiles                                                                 \
    regression                                                                \
    ridge_regression                                                          \
    sorting                                                                   \
    stump                                                                     \
    svd                                                                       \
    svm                                                                       \
    tree_utils                                                                \
    weak_learner


CORE.SERVICES       := compression            \
                       data_management

JJ.ALGORITHMS       := adaboost                                                  \
                       adaboost/prediction                                       \
                       adaboost/quality_metric_set                               \
                       adaboost/training                                         \
                       association_rules                                         \
                       bacon_outlier_detection                                   \
                       binary_adaboost                                           \
                       binary_adaboost/prediction                                \
                       binary_adaboost/quality_metric_set                        \
                       binary_adaboost/training                                  \
                       boosting                                                  \
                       boosting/prediction                                       \
                       boosting/training                                         \
                       brownboost                                                \
                       brownboost/prediction                                     \
                       brownboost/quality_metric_set                             \
                       brownboost/training                                       \
                       cholesky                                                  \
                       classifier                                                \
                       classifier/prediction                                     \
                       classifier/quality_metric                                 \
                       classifier/quality_metric/binary_confusion_matrix         \
                       classifier/quality_metric/multi_class_confusion_matrix    \
                       classifier/training                                       \
                       cordistance                                               \
                       cosdistance                                               \
                       covariance                                                \
                       dbscan                                                    \
                       decision_forest                                           \
                       decision_forest/classification                            \
                       decision_forest/classification/prediction                 \
                       decision_forest/classification/training                   \
                       decision_forest/regression                                \
                       decision_forest/regression/prediction                     \
                       decision_forest/regression/training                       \
                       decision_tree                                             \
                       decision_tree/classification                              \
                       decision_tree/classification/prediction                   \
                       decision_tree/classification/training                     \
                       decision_tree/regression                                  \
                       decision_tree/regression/prediction                       \
                       decision_tree/regression/training                         \
                       distributions                                             \
                       distributions/bernoulli                                   \
                       distributions/normal                                      \
                       distributions/uniform                                     \
                       engines                                                   \
                       engines/mcg59                                             \
                       engines/mt19937                                           \
                       engines/mt2203                                            \
                       em_gmm                                                    \
                       em_gmm/init                                               \
                       gbt                                                       \
                       gbt/classification                                        \
                       gbt/classification/prediction                             \
                       gbt/classification/training                               \
                       gbt/regression                                            \
                       gbt/regression/prediction                                 \
                       gbt/regression/training                                   \
                       gbt/training                                              \
                       implicit_als                                              \
                       implicit_als/prediction                                   \
                       implicit_als/prediction/ratings                           \
                       implicit_als/training                                     \
                       implicit_als/training/init                                \
                       kernel_function                                           \
                       kernel_function/linear                                    \
                       kernel_function/rbf                                       \
                       kdtree_knn_classification                                 \
                       kdtree_knn_classification/prediction                      \
                       kdtree_knn_classification/training                        \
                       kmeans                                                    \
                       kmeans/init                                               \
                       lasso_regression                                          \
                       lasso_regression/training                                 \
                       lasso_regression/prediction                               \
                       linear_regression                                         \
                       linear_regression/prediction                              \
                       linear_regression/quality_metric                          \
                       linear_regression/quality_metric_set                      \
                       linear_regression/training                                \
                       logistic_regression                                       \
                       logistic_regression/prediction                            \
                       logistic_regression/training                              \
                       logitboost                                                \
                       logitboost/prediction                                     \
                       logitboost/quality_metric_set                             \
                       logitboost/training                                       \
                       low_order_moments                                         \
                       math/abs                                                  \
                       math/logistic                                             \
                       math/relu                                                 \
                       math/smoothrelu                                           \
                       math/softmax                                              \
                       math/tanh                                                 \
                       multi_class_classifier                                    \
                       multi_class_classifier/prediction                         \
                       multi_class_classifier/quality_metric_set                 \
                       multi_class_classifier/training                           \
                       multinomial_naive_bayes                                   \
                       multinomial_naive_bayes/prediction                        \
                       multinomial_naive_bayes/quality_metric_set                \
                       multinomial_naive_bayes/training                          \
                       multivariate_outlier_detection                            \
                       multivariate_outlier_detection/defaultdense               \
                       multivariate_outlier_detection/bacondense                 \
                       neural_networks                                           \
                       neural_networks/initializers                              \
                       neural_networks/initializers/uniform                      \
                       neural_networks/initializers/xavier                       \
                       neural_networks/initializers/gaussian                     \
                       neural_networks/initializers/truncated_gaussian           \
                       neural_networks/layers                                    \
                       neural_networks/layers/abs                                \
                       neural_networks/layers/average_pooling1d                  \
                       neural_networks/layers/average_pooling2d                  \
                       neural_networks/layers/average_pooling3d                  \
                       neural_networks/layers/batch_normalization                \
                       neural_networks/layers/concat                             \
                       neural_networks/layers/convolution2d                      \
                       neural_networks/layers/transposed_conv2d                  \
                       neural_networks/layers/dropout                            \
                       neural_networks/layers/eltwise_sum                        \
                       neural_networks/layers/fullyconnected                     \
                       neural_networks/layers/logistic                           \
                       neural_networks/layers/loss                               \
                       neural_networks/layers/lrn                                \
                       neural_networks/layers/maximum_pooling1d                  \
                       neural_networks/layers/maximum_pooling2d                  \
                       neural_networks/layers/maximum_pooling3d                  \
                       neural_networks/layers/reshape                            \
                       neural_networks/layers/stochastic_pooling2d               \
                       neural_networks/layers/spatial_pooling2d                  \
                       neural_networks/layers/spatial_average_pooling2d          \
                       neural_networks/layers/spatial_maximum_pooling2d          \
                       neural_networks/layers/spatial_stochastic_pooling2d       \
                       neural_networks/layers/pooling1d                          \
                       neural_networks/layers/pooling2d                          \
                       neural_networks/layers/pooling3d                          \
                       neural_networks/layers/prelu                              \
                       neural_networks/layers/elu                                \
                       neural_networks/layers/relu                               \
                       neural_networks/layers/logistic_cross                     \
                       neural_networks/layers/smoothrelu                         \
                       neural_networks/layers/softmax                            \
                       neural_networks/layers/softmax_cross                      \
                       neural_networks/layers/split                              \
                       neural_networks/layers/tanh                               \
                       neural_networks/layers/lcn                                \
                       neural_networks/layers/locallyconnected2d                 \
                       neural_networks/prediction                                \
                       neural_networks/training                                  \
                       normalization/minmax                                      \
                       normalization/zscore                                      \
                       optimization_solver                                       \
                       optimization_solver/cross_entropy_loss                    \
                       optimization_solver/logistic_loss                         \
                       optimization_solver/objective_function                    \
                       optimization_solver/sum_of_functions                      \
                       optimization_solver/mse                                   \
                       optimization_solver/precomputed                           \
                       optimization_solver/iterative_solver                      \
                       optimization_solver/sgd                                   \
                       optimization_solver/saga                                  \
                       optimization_solver/coordinate_descent                    \
                       optimization_solver/lbfgs                                 \
                       optimization_solver/adagrad                               \
                       pca                                                       \
                       pca/quality_metric                                        \
                       pca/quality_metric_set                                    \
                       pca/transform                                             \
                       pivoted_qr                                                \
                       qr                                                        \
                       quality_metric                                            \
                       quality_metric_set                                        \
                       quantiles                                                 \
                       ridge_regression                                          \
                       ridge_regression/prediction                               \
                       ridge_regression/training                                 \
                       regression                                                \
                       regression/training                                       \
                       regression/prediction                                     \
                       sorting                                                   \
                       stump                                                     \
                       stump/prediction                                          \
                       stump/training                                            \
                       stump/classification                                      \
                       stump/classification/training                             \
                       stump/classification/prediction                           \
                       stump/regression                                          \
                       stump/regression/training                                 \
                       stump/regression/prediction                               \
                       svd                                                       \
                       svm                                                       \
                       svm/prediction                                            \
                       svm/quality_metric_set                                    \
                       svm/training                                              \
                       tree_utils                                                \
                       tree_utils/classification                                 \
                       tree_utils/regression                                     \
                       univariate_outlier_detection                              \
                       weak_learner                                              \
                       weak_learner/prediction                                   \
                       weak_learner/training

JJ.DATA_MANAGEMENT  := data                                                      \
                       data_source                                               \
                       compression                                               \
                       compression/bzip2                                         \
                       compression/lzo                                           \
                       compression/rle                                           \
                       compression/zlib
