SET(MAKE_CROSS_COMPILING TRUE)
SET(CMAKE_SYSTEM_NAME "Linux")
SET(CMAKE_SYSTEM_PROCESSOR "riscv64")

SET(CMAKE_SYSROOT $ENV{ONEDAL_SYSROOT})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

find_program(CMAKE_C_COMPILER NAMES clang)
SET(CMAKE_C_COMPILER_TARGET riscv64-linux-gnu)

find_program(CMAKE_CXX_COMPILER NAMES clang++)
SET(CMAKE_CXX_COMPILER_TARGET riscv64-linux-gnu)

