/* file: brownboostqualitymetricsetbatch.cpp */
/*******************************************************************************
* Copyright 2014-2018 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "daal.h"
#include "brownboost/quality_metric_set/JQualityMetricSetBatch.h"

using namespace daal::algorithms::brownboost::quality_metric_set;

/*
 * Class:     com_intel_daal_algorithms_brownboost_quality_metric_set_QualityMetricSetBatch
 * Method:    cInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_brownboost_quality_1metric_1set_QualityMetricSetBatch_cInit
(JNIEnv *, jobject)
{
    jlong addr = 0;
    addr = (jlong)(new Batch());
    return addr;
}
