/* file: model.cpp */
/*******************************************************************************
* Copyright 2014-2018 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_brownboost_Batch */

#include "daal.h"
#include "brownboost/JModel.h"

using namespace daal;
using namespace daal::algorithms;
using namespace daal::data_management;

/*
 * Class:     com_intel_daal_algorithms_brownboost_Model
 * Method:    cGetAlpha
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_brownboost_Model_cGetAlpha
(JNIEnv *env, jobject thisObj, jlong modelAddr)
{
    NumericTablePtr *nt = new NumericTablePtr();
    brownboost::ModelPtr res =
        services::staticPointerCast<brownboost::Model, SerializationIface>(*(brownboost::ModelPtr *)modelAddr);

    *nt = res->getAlpha();

    return (jlong)nt;
}
