/* file: multiclassconfusionmatrixparameter.cpp */
/*******************************************************************************
* Copyright 2014-2016 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixParameter */

#include <jni.h>
#include "daal.h"
#include "classifier/quality_metric/multi_class_confusion_matrix/JMultiClassConfusionMatrixParameter.h"

using namespace daal;
//using namespace daal::algorithms;
using namespace daal::data_management;
using namespace daal::algorithms::classifier;
using namespace daal::algorithms::classifier::quality_metric;
using namespace daal::algorithms::classifier::quality_metric::multiclass_confusion_matrix;

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixParameter
 * Method:    cSetBeta
 * Signature: (JD)V
 */
JNIEXPORT void
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixParameter_cSetBeta
  (JNIEnv *, jobject, jlong parAddr, jdouble beta)
{
    (*(multiclass_confusion_matrix::Parameter *)parAddr).beta = beta;
}

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixParameter
 * Method:    cGetBeta
 * Signature: (J)D
 */
JNIEXPORT jdouble
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixParameter_cGetBeta
  (JNIEnv *, jobject, jlong parAddr)
{
    return (jdouble)(*(multiclass_confusion_matrix::Parameter *)parAddr).beta;
}
