/* file: parameter.cpp */
/*******************************************************************************
* Copyright 2014-2016 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_classifier_Parameter */

#include "daal.h"
#include "classifier/JParameter.h"

using namespace daal;
using namespace daal::algorithms;
using namespace daal::data_management;

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_classifier_Parameter_cSetNClasses
(JNIEnv *env, jobject thisObj, jlong parAddr, jlong val )
{
    (*(classifier::Parameter *)parAddr).nClasses = val;
}

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_classifier_Parameter_cGetNClasses
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return (jlong)(*(classifier::Parameter *)parAddr).nClasses;
}
