/* file: parameter.cpp */
/*******************************************************************************
* Copyright 2014-2019 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_covariance_Offline */

#include "daal.h"
#include "covariance/JParameter.h"
#include "covariance/JOutputMatrixType.h"

using namespace daal;
using namespace daal::algorithms;

#define CovMatrix com_intel_daal_algorithms_covariance_OutputMatrixType_CovarianceMatrix
#define CorMatrix com_intel_daal_algorithms_covariance_OutputMatrixType_CorrelationMatrix

/*
 * Class:     com_intel_daal_algorithms_covariance_Parameter
 * Method:    cSetDataSet
 * Signature:(JIJ)I
 */
JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_covariance_Parameter_cSetOutputDataType
(JNIEnv *env, jobject thisObj, jlong parAddr, jint id)
{
    if(id == CovMatrix)
    {
        (*(covariance::Parameter *)parAddr).outputMatrixType = covariance::covarianceMatrix;
    }
    else if(id == CorMatrix)
    {
        (*(covariance::Parameter *)parAddr).outputMatrixType = covariance::correlationMatrix;
    }
}

JNIEXPORT jint JNICALL Java_com_intel_daal_algorithms_covariance_Parameter_cGetOutputDataType
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    return(jint)(*(covariance::Parameter *)parAddr).outputMatrixType;
}

/*
 * Class:     com_intel_daal_algorithms_covariance_Parameter
 * Method:    cSetCParameterObject
 * Signature: (JJIIII)J
 */
JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_covariance_Parameter_cSetCParameterObject
(JNIEnv *env, jobject thisObj, jlong parameterAddr, jlong algAddr)
{
    using namespace daal::services;
    using namespace daal::algorithms;
    using namespace daal::data_management;

    SharedPtr<AlgorithmIface> *algShPtr = (SharedPtr<AlgorithmIface> *)algAddr;
    if(dynamicPointerCast<covariance::DistributedIface<step2Master>, AlgorithmIface>(*algShPtr))
    {
        staticPointerCast<covariance::DistributedIface<step2Master>, AlgorithmIface>(*algShPtr)->parameter = *((covariance::Parameter *)parameterAddr);
    }
    else
    {
        staticPointerCast<covariance::BatchImpl, AlgorithmIface>(*algShPtr)->parameter = *((covariance::Parameter *)parameterAddr);
    }
}
