/* file: multiclassconfusionmatrixbatch.cpp */
/*******************************************************************************
* Copyright 2014-2019 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "daal.h"
#include "classifier/quality_metric/multi_class_confusion_matrix/JMultiClassConfusionMatrixBatch.h"
#include "classifier/quality_metric/multi_class_confusion_matrix/JMultiClassConfusionMatrixMethod.h"

#include "common_helpers.h"

USING_COMMON_NAMESPACES();
using namespace daal::algorithms::classifier::quality_metric::multiclass_confusion_matrix;
using namespace daal::algorithms::classifier::quality_metric;

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixBatch
 * Method:    cInit
 * Signature: (II)J
 */
JNIEXPORT jlong
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixBatch_cInit
  (JNIEnv *, jobject, jint prec, jint method)
{
    return jniBatch<multiclass_confusion_matrix::Method, Batch, defaultDense>::newObj(prec, method);
}
/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixBatch
 * Method:    cSetResult
 * Signature: (JIIJ)V
 */
JNIEXPORT void
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixBatch_cSetResult
  (JNIEnv *, jobject, jlong algAddr, jint prec, jint method, jlong resultAddr)
{
    jniBatch<multiclass_confusion_matrix::Method, Batch, defaultDense>::
        setResult<multiclass_confusion_matrix::Result>(prec, method, algAddr, resultAddr);
}

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixBatch
 * Method:    cInitParameter
 * Signature: (JII)J
 */
JNIEXPORT jlong
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixBatch_cInitParameter
  (JNIEnv *, jobject, jlong algAddr, jint prec, jint method)
{
    return jniBatch<multiclass_confusion_matrix::Method, Batch, defaultDense>::getParameter(prec, method, algAddr);
}

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixBatch
 * Method:    cGetInput
 * Signature: (JII)J
 */
JNIEXPORT jlong
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixBatch_cGetInput
  (JNIEnv *, jobject, jlong algAddr, jint prec, jint method)
{
    return jniBatch<multiclass_confusion_matrix::Method, Batch, defaultDense>::getInput(prec, method, algAddr);
}

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixBatch
 * Method:    cGetResult
 * Signature: (JII)J
 */
JNIEXPORT jlong
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixBatch_cGetResult
  (JNIEnv *, jobject, jlong algAddr, jint prec, jint method)
{
    return jniBatch<multiclass_confusion_matrix::Method, Batch, defaultDense>::getResult(prec, method, algAddr);
}

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixBatch
 * Method:    cClone
 * Signature: (JII)J
 */
JNIEXPORT jlong
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixBatch_cClone
  (JNIEnv *, jobject, jlong algAddr, jint prec, jint method)
{
    return jniBatch<multiclass_confusion_matrix::Method, Batch, defaultDense>::getClone(prec, method, algAddr);
}
