/* file: multiclassconfusionmatrixparameter.cpp */
/*******************************************************************************
* Copyright 2014-2018 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixParameter */

#include <jni.h>
#include "daal.h"
#include "classifier/quality_metric/multi_class_confusion_matrix/JMultiClassConfusionMatrixParameter.h"

using namespace daal;
//using namespace daal::algorithms;
using namespace daal::data_management;
using namespace daal::algorithms::classifier;
using namespace daal::algorithms::classifier::quality_metric;
using namespace daal::algorithms::classifier::quality_metric::multiclass_confusion_matrix;

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixParameter
 * Method:    cSetBeta
 * Signature: (JD)V
 */
JNIEXPORT void
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixParameter_cSetBeta
  (JNIEnv *, jobject, jlong parAddr, jdouble beta)
{
    (*(multiclass_confusion_matrix::Parameter *)parAddr).beta = beta;
}

/*
 * Class:     com_intel_daal_algorithms_classifier_quality_metric_multi_class_confusion_matrix_MultiClassConfusionMatrixParameter
 * Method:    cGetBeta
 * Signature: (J)D
 */
JNIEXPORT jdouble
 JNICALL Java_com_intel_daal_algorithms_classifier_quality_1metric_multi_1class_1confusion_1matrix_MultiClassConfusionMatrixParameter_cGetBeta
  (JNIEnv *, jobject, jlong parAddr)
{
    return (jdouble)(*(multiclass_confusion_matrix::Parameter *)parAddr).beta;
}
