/* file: parameter.cpp */
/*******************************************************************************
* Copyright 2014-2018 Intel Corporation.
*
* This software and the related documents are Intel copyrighted  materials,  and
* your use of  them is  governed by the  express license  under which  they were
* provided to you (License).  Unless the License provides otherwise, you may not
* use, modify, copy, publish, distribute,  disclose or transmit this software or
* the related documents without Intel's prior written permission.
*
* This software and the related documents  are provided as  is,  with no express
* or implied  warranties,  other  than those  that are  expressly stated  in the
* License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>/* Header for class com_intel_daal_algorithms_multinomial_naive_bayes_Batch */

#include "daal.h"
#include "multinomial_naive_bayes/JParameter.h"

using namespace daal;
using namespace daal::algorithms;
using namespace daal::data_management;
using namespace daal::services;

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_multinomial_1naive_1bayes_Parameter_cSetPriorClassEstimates
(JNIEnv *env, jobject thisObj, jlong parAddr, jlong ntAddr)
{
    SerializationIfacePtr *ntShPtr = (SerializationIfacePtr *)ntAddr;
    (*(multinomial_naive_bayes::Parameter *)parAddr).priorClassEstimates = staticPointerCast<NumericTable, SerializationIface>(*ntShPtr);
}

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_multinomial_1naive_1bayes_Parameter_cGetPriorClassEstimates
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    SerializationIfacePtr *ntShPtr = new SerializationIfacePtr();
    *ntShPtr = (*(multinomial_naive_bayes::Parameter *)parAddr).priorClassEstimates;
    return (jlong)ntShPtr;
}

JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_multinomial_1naive_1bayes_Parameter_cSetAlpha
(JNIEnv *env, jobject thisObj, jlong parAddr, jlong ntAddr)
{
    SerializationIfacePtr *ntShPtr = (SerializationIfacePtr *)ntAddr;
    (*(multinomial_naive_bayes::Parameter *)parAddr).alpha = staticPointerCast<NumericTable, SerializationIface>(*ntShPtr);
}

JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_multinomial_1naive_1bayes_Parameter_cGetAlpha
(JNIEnv *env, jobject thisObj, jlong parAddr)
{
    SerializationIfacePtr *ntShPtr = new SerializationIfacePtr();
    *ntShPtr = (*(multinomial_naive_bayes::Parameter *)parAddr).alpha;
    return (jlong)ntShPtr;
}
