/* file: explained_variance_input.cpp */
/*******************************************************************************
* Copyright 2014-2019 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "daal.h"
#include "com_intel_daal_algorithms_pca_quality_metric_ExplainedVarianceInput.h"
#include "common_helpers.h"

USING_COMMON_NAMESPACES();
using namespace daal::algorithms::pca::quality_metric;
using namespace daal::algorithms::pca::quality_metric::explained_variance;

#include "com_intel_daal_algorithms_pca_quality_metric_ExplainedVarianceInputId.h"
#define EigenValues com_intel_daal_algorithms_pca_quality_metric_ExplainedVarianceInputId_eigenValuesId

/*
* Class:     com_intel_daal_algorithms_pca_quality_metric_ExplainedVarianceInput
* Method:    cSetInputTable
* Signature: (JIJ)V
*/
JNIEXPORT void JNICALL Java_com_intel_daal_algorithms_pca_quality_1metric_ExplainedVarianceInput_cSetInputTable(JNIEnv *, jobject, jlong resAddr,
                                                                                                                jint id, jlong ntAddr)
{
    if (id == EigenValues)
        jniInput<explained_variance::Input>::set<explained_variance::InputId, NumericTable>(resAddr, explained_variance::eigenvalues, ntAddr);
}

/*
* Class:     com_intel_daal_algorithms_pca_quality_metric_ExplainedVarianceInput
* Method:    cGetInputTable
* Signature: (JI)J
*/
JNIEXPORT jlong JNICALL Java_com_intel_daal_algorithms_pca_quality_1metric_ExplainedVarianceInput_cGetInputTable(JNIEnv *, jobject, jlong inputAddr,
                                                                                                                 jint id)
{
    if (id != EigenValues) return (jlong)0;

    return jniInput<explained_variance::Input>::get<explained_variance::InputId, NumericTable>(inputAddr, id);
}
