package(default_visibility = ["//visibility:public"])
load("@onedal//dev/bazel:daal.bzl", "daal_module")

daal_module(
    name = "common",
    auto = True,
    deps = [
        "@onedal//cpp/daal:core",
    ],
)
