name: oneDAL nightly build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_win:
    name: build Windows
    if: github.repository == 'oneapi-src/oneDAL'
    runs-on: windows-2022

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
      - name: Install DPC++
        run: |
          $env:PATH="C:\msys64\usr\bin;$env:PATH"
          echo $env:PATH=C:\msys64\usr\bin;$env:PATH >> $env.GITHUB_ENV
          pip install cpufeature
          pacman -S -y --noconfirm zip dos2unix tree wget gcc
          echo "Download intel DPC++ compiler"
          wget -q -O dpcpp_installer.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3165d8c7-088f-410f-9723-6d8ee88d9e5b/w_dpcpp-cpp-compiler_p_2024.1.2.505_offline.exe
          echo "Unpacking DPC++ installer"
          Start-Process ".\dpcpp_installer.exe" -ArgumentList "--s --x --f oneAPI" -Wait
          echo "Installing DPC++ compiler"
          Start-Process ".\oneAPI\bootstrapper.exe" -ArgumentList "-s --eula=accept --install-dir=dpcpp" -Wait
          # This can take 20 minutes...
          echo "DPC++ install complete"
      - name: System Info
        run: |
          bash .ci/scripts/describe_system.sh
      - name: Make daal
        shell: cmd
        run: |
          call .\.ci\scripts\build.bat daal vc avx2
      - name: Make onedal
        shell: cmd
        run: |
          call .\.ci\scripts\build.bat onedal_c vc avx2
      - name: Make oneapi_dpc
        shell: cmd
        run: |
          call .\dpcpp\compiler\latest\env\vars.bat
          call .\.ci\scripts\build.bat onedal_dpc vc avx2
